/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gkspizza;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author gari9870
 * @date Jan 14, 2024
 * @filename GameFrame
 * @description This class is the main frame that holds all the components required to run our game. 
 */
public class GameFrame extends javax.swing.JFrame {


    
    //important panels
    private GamePanel panGame;
    private InstructionsPanel howPanel;
    
    //images
    private BufferedImage titleScreen;
     
    //main thread to run 
    static Thread mainThread = new Thread() {
        public void run() {
            new GameFrame().setVisible(true);

        }
    };

    /**
     * Creates new frame frmGame
     */
    public GameFrame() {

        initComponents();
        loadImages();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panStartScreen = new javax.swing.JPanel(){  //paintComponent happens on object creation and when
            //any changes occur to the frame (size change, new objects added.
                // etc.)
            @Override // this means that we are replacing the old
            //method that is prebuilt with a new one.
            public void paintComponent(Graphics g) {
                super.paintComponent(g); //calls the old paintComponent method
                draw(g);//calls the draw method
            }
        }
        ;
        startButton = new javax.swing.JButton();
        InstructionsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        panStartScreen.setBackground(new java.awt.Color(204, 204, 255));
        panStartScreen.setMaximumSize(new java.awt.Dimension(820, 800));
        panStartScreen.setMinimumSize(new java.awt.Dimension(820, 800));
        panStartScreen.setPreferredSize(new java.awt.Dimension(820, 800));

        startButton.setFont(new java.awt.Font("Rockwell Condensed", 0, 60)); // NOI18N
        startButton.setText("START");
        startButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        InstructionsButton.setFont(new java.awt.Font("Rockwell Condensed", 0, 60)); // NOI18N
        InstructionsButton.setText("HOW TO PLAY");
        InstructionsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        InstructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panStartScreenLayout = new javax.swing.GroupLayout(panStartScreen);
        panStartScreen.setLayout(panStartScreenLayout);
        panStartScreenLayout.setHorizontalGroup(
            panStartScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panStartScreenLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(startButton)
                .addGap(110, 110, 110)
                .addComponent(InstructionsButton)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        panStartScreenLayout.setVerticalGroup(
            panStartScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panStartScreenLayout.createSequentialGroup()
                .addContainerGap(600, Short.MAX_VALUE)
                .addGroup(panStartScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(InstructionsButton))
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panStartScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panStartScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        //this will start the game. It generates a new GamePanel which is what the game is played on 
        panStartScreen.setVisible(false);
        panGame = new GamePanel(this);
        this.add(getPanGame());

        panGame.setSize(getPanGame().getPreferredSize());
        panGame.setLocation(0, 0);
        panGame.setVisible(true);

        //starts game loop
        panGame.startGameThread();
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void InstructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionsButtonActionPerformed
        // This code is run whne the "HOW TO PLAY" button is clicked. If so, it will redirect the user to an instructions panel explaining how to play the game:
        
        panStartScreen.setVisible(false);
        howPanel = new InstructionsPanel(this);
        this.add(howPanel);

        howPanel.setSize(getHowPanel().getPreferredSize());
        howPanel.setLocation(0, 0);
        howPanel.setVisible(true);
    }//GEN-LAST:event_InstructionsButtonActionPerformed

    
      /**
     * this method is used to terminate the game operations and return to the home screen.  
     */
    public void quitGame() {

          
        panStartScreen.setVisible(true);
        this.remove(getPanGame());
    }

    /**
     * this method is used to return to the home screen, after the user finishes reading the instructions
     */
    public void backHome() {
        panStartScreen.setVisible(true);
        this.remove(getHowPanel());
    }
    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  
        //</editor-fold>  

        /* Create and display the form */
        mainThread.start();
//        java.awt.EventQueue.invokeLater(mainThread); // waht does this do again?

    }

    /**
     *  This method is used to draw anything on to this game frame. For our purposes, it is used to draw our custom title screen image
     * @param g a basic painting tool. It is used to create a more sophisticated and efficient painting tool from the Graphics2D class, "g2". 
     */
    public void draw(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;

        g2.drawImage(this.getTitleScreen(), 0, 0, this.getWidth(), this.getHeight(), null);

    }

    /**
     * this method is used to load in any images that need to be drawn in our frame. We primarily use it to load our game's title screen
     */
    private void loadImages() {
        try {
            this.titleScreen = ImageIO.read(getClass().getResourceAsStream("/images/screens/title screen.png"));
        } catch (IOException ex) {
            Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InstructionsButton;
    private javax.swing.JPanel panStartScreen;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the GamePanel which controls all of the game's functions
     */
    public GamePanel getPanGame() {
        return panGame;
    }

    /**
     * @return the panel with the game instructions
     */
    public InstructionsPanel getHowPanel() {
        return howPanel;
    }

    /**
     * @return the titleScreen's image
     */
    public BufferedImage getTitleScreen() {
        return titleScreen;
    }
}
