/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gkspizza;

import gkspizza.GameFrame;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author darm4080
 *  @date Jan 22, 2024
 * @filename InstructionsPanel
 * @description This class uses JPanels for visual representation of our game's instructions
 */
public class InstructionsPanel extends javax.swing.JPanel {

    BufferedImage backImage; // background image
    
    GameFrame main; // used to reference the frame this panel is displayed on
    
    
    
    /**
     * Creates new form InstructionsPanel
     * @param main this panel's parent container
     * 
     */
  
    public InstructionsPanel(GameFrame main) {
        initComponents();
        this.main = main;
        loadImages();
    }

    /**
     *this method is used to load in any images that need to be drawn in our frame. We primarily use it to load the image that explains how to play the game
     */
    private void loadImages() {
        //initializing images
        try {
            backImage = ImageIO.read(getClass().getResourceAsStream("/images/screens/howToPlay.png"));
        } catch (IOException e) {
            System.out.println("Image not FOund");
        }

    }

    /**
     *  This method is used to draw anything on to this JPanel. For our purposes, it is used to draw the image presenting game instructions.
     * @param g a basic painting tool. It is used to create a more sophisticated and efficient painting tool from the Graphics2D class, "g2". 
     */
    private void draw(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.drawImage(backImage, 0, 0, 800, 800, null);
    }

    /**
     *  paintComponent happens on object creation and when
     * any changes occur to the frame (size change, new objects added.
     * etc.)
     * @param g a basic painting tool
     */
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g); //calls the old paintComponent method
        draw(g);//calls the draw method
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        returnButton.setFont(new java.awt.Font("Rockwell Condensed", 0, 18)); // NOI18N
        returnButton.setText("Back");
        returnButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(671, Short.MAX_VALUE)
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(756, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        this.main.backHome();
        this.setVisible(false);
        
    }//GEN-LAST:event_returnButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
