/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gkspizza.appliances;

import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author gari9870
 * @date Jan 14, 2024
 * @filename InteractFrame
 * @description: This class is used to handle and display any processes
 * initiated through interactions between the user and the various appliances in
 * our game.
 */
public class InteractFrame extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form frmInteract
     *
     * @param gameObject represents the appliance whose interaction process is
     * being displayed through this frame
     */
    public InteractFrame(Appliance gameObject) {
        initComponents();
        this.setVisible(true);
        this.gameObject = gameObject;

        this.setDefaultCloseOperation(0); // this ensures that the user cannot use the default red X button to leave the frame, 
                                                  //and instead must use a custom button that can be programmed to execute additional functions upon closing the frame
    }

    //used to make an instance of the gameObject this frame is being created for
    private final Appliance gameObject;

    //These variables are utilized in the game loop and are important to ensure that interactions with various stations do not interfere with the main game loop
    private Thread interactThread;
    private boolean running = false;
    private final int FPS = 60;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panDraw = new javax.swing.JPanel(){

            //paintComponent happens on object creation and when
            //any changes occur to the frame (size change, new objects added.
                // etc.)
            @Override // this means that we are replacing the old
            //method that is prebuilt with a new one.
            public void paintComponent(Graphics g) {
                super.paintComponent(g); //calls the old paintComponent method
                Graphics2D g2 = (Graphics2D) g;
                draw(g2);//calls the draw method
            }

        };
        backButton = new javax.swing.JButton();
        stationLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 800));
        setResizable(false);

        panDraw.setMaximumSize(new java.awt.Dimension(820, 800));
        panDraw.setMinimumSize(new java.awt.Dimension(820, 800));

        backButton.setBackground(new java.awt.Color(255, 204, 204));
        backButton.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        backButton.setText("Back to Restaurant");
        backButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        stationLbl.setFont(new java.awt.Font("Rockwell Condensed", 0, 48)); // NOI18N
        stationLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stationLbl.setText("label");

        javax.swing.GroupLayout panDrawLayout = new javax.swing.GroupLayout(panDraw);
        panDraw.setLayout(panDrawLayout);
        panDrawLayout.setHorizontalGroup(
            panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDrawLayout.createSequentialGroup()
                .addGap(0, 227, Short.MAX_VALUE)
                .addComponent(stationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(backButton)
                .addGap(16, 16, 16))
        );
        panDrawLayout.setVerticalGroup(
            panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDrawLayout.createSequentialGroup()
                .addGroup(panDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDrawLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backButton))
                .addGap(0, 776, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        this.gameObject.exitFrame();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InteractFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InteractFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InteractFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InteractFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    /**
     * Used to start a separate thread for the interaction process
     */
    public void startThread() {
        interactThread = new Thread(this);
        interactThread.start();
        running = true;
    }

    /**
     * Used to stop the interactThread
     */
    public void stopThread() {
        running = false;
        try{
            this.interactThread.join();
        }catch (InterruptedException e){
            e.printStackTrace();
        }

    }

    /**
     * This method is used to quit the interaction process and return to the
     * main game screen
     */
    public void quitInteraction() {

        stopThread();
        this.dispose();
    }

    /**
     * This method is used to run the interaction game loop
     */
    @Override
    public void run() {
        this.requestFocus();
        double drawInterval = 1000000000 / FPS;
        double delta = 0;
        long lastTime = System.nanoTime();
        long currentTime;
        long timer = 0;

        while (interactThread != null && running) { // this will run forever until the panel is closed

            currentTime = System.nanoTime();

            delta += (currentTime - lastTime) / drawInterval;
            timer += (currentTime - lastTime);
            lastTime = currentTime;

            if (delta >= 1) { // game loop
                repaint();
                delta--;
            }

        }
    }

    /**
     * This method is used to draw anything on to this  frame. For our
     * purposes, it is used to display the appliance's personalized UI.
     *
     * @param g a basic painting tool. It is used to create a more sophisticated
     * and efficient painting tool from the Graphics2D class, "g2".
     */
    private void draw(Graphics2D g) {
        Graphics2D g2 = (Graphics2D) g;
        this.gameObject.drawFrame(g2);
    }

    /**
     *
     * @return the button used to leave the interaction frame
     */
    public JButton getBackButton() {
        return backButton;
    }

    /**
     *
     * @return the drawing panel
     */
    public JPanel getPanDraw() {
        return panDraw;
    }

    /**
     *
     * @return the label which tells user which station they are currently working at
     */
    public JLabel getStationLbl() {
        return stationLbl;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel panDraw;
    private javax.swing.JLabel stationLbl;
    // End of variables declaration//GEN-END:variables
}
